#
# IMPORTANT.  OS X support is so experimental that you have to specifically
# request to have it enabled, on a per-repository basis.  See
# http://docs.travis-ci.com/user/multi-os/#Manual-intervention-required
#
# This file will still work, without OS X enabled, it just won't run those
# tests.
#
language: python

os:
    - linux
    # - osx

# xenial = Ubuntu 16.04
# bionic = Ubuntu 18.04
dist: xenial
# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng
python:
    # - 3.5
    - 3.6
    - 3.7
    - 3.8
env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - MAIN_CMD='python setup.py'
        - DESIUTIL_VERSION=2.0.3
        - SPHINX_VERSION='<2.0'
    matrix:
        - SETUP_CMD='egg_info'
        - SETUP_CMD='bdist_egg'
        - SETUP_CMD='test'

matrix:
    # Don't wait for allowed failures.
    fast_finish: true

    # OS X support is still experimental, so don't penalize failures.
    allow_failures:
        - os: osx
        - os: linux
          python: 3.6
          env: MAIN_CMD='pycodestyle' SETUP_CMD='--count py/desidatamodel'

    include:
        # Check for sphinx doc build warnings.
        - os: linux
          python: 3.6
          env: SETUP_CMD='build_sphinx --warning-is-error'

        # Coverage test, pass the results to coveralls.
        - os: linux
          python: 3.6
          env: MAIN_CMD='coverage' SETUP_CMD='run --source=desidatamodel setup.py test'

        - os: linux
          python: 3.6
          env: SETUP_CMD='test' ASTROPY_VERSION='>=4.0'

        - os: linux
          python: 3.6
          env: SETUP_CMD='test' ASTROPY_VERSION='<4.0'

        # PEP 8 compliance.
        - os: linux
          python: 3.6
          env: MAIN_CMD='pycodestyle' SETUP_CMD='--count py/desidatamodel'

# before_install:
#     - curl ipinfo.io

install:
    - if [[ $MAIN_CMD == 'pycodestyle' ]]; then pip install pycodestyle; fi
    - if [[ $SETUP_CMD == build_sphinx* ]]; then pip install Sphinx==${SPHINX_VERSION}; fi
    - if [[ $MAIN_CMD == 'coverage' ]]; then pip install coverage coveralls; fi
    - pip install git+https://github.com/desihub/desiutil.git@${DESIUTIL_VERSION}#egg=desiutil
    - if [[ $SETUP_CMD == 'test' || $MAIN_CMD == 'coverage' ]]; then pip install -r requirements.txt; fi

script:
    - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $MAIN_CMD == 'coverage' ]]; then coveralls; fi
